Simulator of 1-dimensional random walk

A person or stock price that starts at position X (integer) and moves up 1 unit or down 1 unit during each minute (integer).  After L minutes, the person or stock ends at position E (integer). Running the code below will ask for start position X, end position E, and amount of time L.  Then it will print the unique paths to go from X to E in L time. 

There are 2 approaches included.  The first approach will randomly iterate through all possible paths until enough unique paths are found.  The second approach will find one possible path and then find the other unique paths via permutations of the first path (more efficient). 

The paths are all printed as numpy arrays grouped in a numpy matrix.  Each row (array) of the matrix is a unique path (a possible path from from X to E in L time). 

Helpful resource: http://mathworld.wolfram.com/RandomWalk1-Dimensional.html

The last cell includes a method to check that the matrices will match from each approach (as long as E, X, L are the same). 

In [52]:
#First Approach

#Instructions: input integer values for X, E, L 
#Output: all unique paths from start price X to end price E over L quanta

#Note: L and (X + E) should be both even or both odd
#Note: L should be greater than or equal to the distance between X and E

#libraries
import random
import math
import sys
import numpy as np
np.set_printoptions(threshold=sys.maxsize)

#input variables
X = int(input('start price X = '))
E = int(input('end price E = '))
L = int(input('quanta L = '))

#binomial coefficient for number of unique paths
tempR = (L + abs(X - E))/2
num_paths = int(math.factorial(L) / ((math.factorial(L - tempR)*(math.factorial(tempR)))))

#random walk function
def walk(n):
    position_array = [X]
    position = position_array[0]
    for i in range(n):
        step = random.choice(['up', 'down'])
        if step == 'up':
            position += 1
            position_array.append(position)
        if step == 'down':
            position -= 1
            position_array.append(position)
    return position_array

#iterator
path_array1 = []
path_matrix = np.array(path_array1)

while len(path_matrix) < num_paths:
    possible_path = walk(L)
    if possible_path[-1] == E and possible_path not in path_array1:
            path_array1.append(possible_path)
            path_matrix = np.array(path_array1)

print('\n')

print('Unique paths ')
print(path_matrix)

print('\n')

print(str(len(path_matrix))+' rows')

print('\n')

print(str(num_paths)+' possible paths with start price '+str(X)+', end price '+str(E)+', and '+str(L)+' quanta')

start price X = 1
end price E = 1
quanta L = 8


Unique paths 
[[ 1  2  1  0  1  0 -1  0  1]
 [ 1  0  1  0  1  0 -1  0  1]
 [ 1  0 -1 -2 -3 -2 -1  0  1]
 [ 1  2  3  2  1  2  3  2  1]
 [ 1  0  1  0 -1  0  1  2  1]
 [ 1  0 -1  0 -1  0  1  0  1]
 [ 1  2  1  0 -1  0 -1  0  1]
 [ 1  0  1  0  1  0  1  2  1]
 [ 1  0 -1 -2 -1  0 -1  0  1]
 [ 1  0  1  2  3  2  3  2  1]
 [ 1  2  1  2  1  0  1  2  1]
 [ 1  0 -1 -2 -1  0  1  2  1]
 [ 1  2  3  2  1  0  1  2  1]
 [ 1  2  1  0  1  2  1  0  1]
 [ 1  0  1  0  1  2  1  0  1]
 [ 1  0  1  2  1  2  3  2  1]
 [ 1  0 -1  0  1  2  1  2  1]
 [ 1  2  3  2  1  2  1  0  1]
 [ 1  0  1  2  1  2  1  0  1]
 [ 1  0  1  2  3  2  1  0  1]
 [ 1  2  1  2  3  4  3  2  1]
 [ 1  2  1  2  1  2  1  2  1]
 [ 1  2  3  2  3  2  3  2  1]
 [ 1  2  1  0 -1  0  1  2  1]
 [ 1  2  3  2  1  0  1  0  1]
 [ 1  2  1  0  1  0  1  2  1]
 [ 1  0 -1  0  1  0  1  2  1]
 [ 1  0 -1  0 -1  0 -1  0  1]
 [ 1  2  3  4  3  2  1  0  1]
 [ 1  0 -1 -2 -1  0  1  0  1]
 [ 1  0  1  0  1  2  1  2  1]
 [ 1  2

In [53]:
#Second Approach

#Finds all unique paths with permutations instead of while / random iterator

#libraries
import random
import math
import sys
import numpy as np
np.set_printoptions(threshold=sys.maxsize)
from itertools import permutations 

#input variables
X = int(input('start price X = '))
E = int(input('end price E = '))
L = int(input('quanta L = '))

#one dimension random walk function
def walk(n):
    position_array = [X]
    position = position_array[0]
    for i in range(n):
        step = random.choice(['up', 'down'])
        if step == 'up':
            position += 1
            position_array.append(position)
        if step == 'down':
            position -= 1
            position_array.append(position)
    return position_array

#use random walk function to find 1 possible path from X to E
possible_path_array = []

while len(possible_path_array) == 0:
    possible_path = walk(L)
    if possible_path[-1] == E:
        possible_path_array.append(possible_path)
        break

#find a delta array that corresponds to 1 possible path above
#a delta array is an array that describes whether position goes up 1 or down 1 in the possible path
delta_array = []
for i in range(len(possible_path_array[0])-1):
    if i == len(possible_path_array[0])-1:
        break
    else: delta_array.append(possible_path_array[0][i+1] - possible_path_array[0][i])


#find all permutations of the delta array, which will describe other possible paths in delta format
delta_perms_list= []
delta_perms = permutations(delta_array)
for i in list(delta_perms):
    if i not in delta_perms_list:
        delta_perms_list.append(i)
        
delta_perms_matrix = np.array(delta_perms_list)

print('\n')
print('Delta Matrix')
print(delta_perms_matrix)
print('\n')

#need to add a column in front of delta matrix to match the shape of paths matrix
#since delta matrix only describes movement up or down, it omits the start position
start_position_column = np.zeros((len(delta_perms_matrix), 1))
for i in range(start_position_column.shape[0]):
    start_position_column[i] = X
path_array = np.hstack((start_position_column, delta_perms_matrix)) 

#add each element in delta matrix (1 or -1) to itself to get the position at each time L
#the result is each possible path for all unique paths from X to E
for i in range(path_array.shape[0]):
    for j in range(path_array.shape[1]):
        if j == path_array.shape[1]-1:
            break
        else: path_array[i][j+1] = path_array[i][j] + path_array[i][j+1] 

print('Unique paths ')
print(path_array.astype(int))

print('\n')

print(str(len(path_array))+' rows')

print('\n')

print(str(len(path_array))+' possible paths with start price '+str(X)+', end price '+str(E)+', and '+str(L)+' quanta')

start price X = 1
end price E = 1
quanta L = 8


Delta Matrix
[[-1  1  1  1 -1 -1  1 -1]
 [-1  1  1  1 -1 -1 -1  1]
 [-1  1  1  1 -1  1 -1 -1]
 [-1  1  1  1  1 -1 -1 -1]
 [-1  1  1 -1  1 -1  1 -1]
 [-1  1  1 -1  1 -1 -1  1]
 [-1  1  1 -1  1  1 -1 -1]
 [-1  1  1 -1 -1  1  1 -1]
 [-1  1  1 -1 -1  1 -1  1]
 [-1  1  1 -1 -1 -1  1  1]
 [-1  1 -1  1  1 -1  1 -1]
 [-1  1 -1  1  1 -1 -1  1]
 [-1  1 -1  1  1  1 -1 -1]
 [-1  1 -1  1 -1  1  1 -1]
 [-1  1 -1  1 -1  1 -1  1]
 [-1  1 -1  1 -1 -1  1  1]
 [-1  1 -1 -1  1  1  1 -1]
 [-1  1 -1 -1  1  1 -1  1]
 [-1  1 -1 -1  1 -1  1  1]
 [-1  1 -1 -1 -1  1  1  1]
 [-1 -1  1  1  1 -1  1 -1]
 [-1 -1  1  1  1 -1 -1  1]
 [-1 -1  1  1  1  1 -1 -1]
 [-1 -1  1  1 -1  1  1 -1]
 [-1 -1  1  1 -1  1 -1  1]
 [-1 -1  1  1 -1 -1  1  1]
 [-1 -1  1 -1  1  1  1 -1]
 [-1 -1  1 -1  1  1 -1  1]
 [-1 -1  1 -1  1 -1  1  1]
 [-1 -1  1 -1 -1  1  1  1]
 [-1 -1 -1  1  1  1  1 -1]
 [-1 -1 -1  1  1  1 -1  1]
 [-1 -1 -1  1  1 -1  1  1]
 [-1 -1 -1  1 -1  1  1  1]
 [-1 -1 -1 -1  1  1 

In [54]:
#Check that the 2 approaches will produce matching unique paths as long as E, X, L are the same
print(path_matrix) #approach 1
print('\n')
print(path_array.astype(int)) #approach 2
print('\n')

matches = 0
for i in range(path_matrix.shape[0]):
    if path_matrix[i] in path_array.astype(int):
        matches += 1
        
print(matches," matches")
print(path_matrix.shape[0]," paths")
print(path_array.shape[0]," paths")

[[ 1  2  1  0  1  0 -1  0  1]
 [ 1  0  1  0  1  0 -1  0  1]
 [ 1  0 -1 -2 -3 -2 -1  0  1]
 [ 1  2  3  2  1  2  3  2  1]
 [ 1  0  1  0 -1  0  1  2  1]
 [ 1  0 -1  0 -1  0  1  0  1]
 [ 1  2  1  0 -1  0 -1  0  1]
 [ 1  0  1  0  1  0  1  2  1]
 [ 1  0 -1 -2 -1  0 -1  0  1]
 [ 1  0  1  2  3  2  3  2  1]
 [ 1  2  1  2  1  0  1  2  1]
 [ 1  0 -1 -2 -1  0  1  2  1]
 [ 1  2  3  2  1  0  1  2  1]
 [ 1  2  1  0  1  2  1  0  1]
 [ 1  0  1  0  1  2  1  0  1]
 [ 1  0  1  2  1  2  3  2  1]
 [ 1  0 -1  0  1  2  1  2  1]
 [ 1  2  3  2  1  2  1  0  1]
 [ 1  0  1  2  1  2  1  0  1]
 [ 1  0  1  2  3  2  1  0  1]
 [ 1  2  1  2  3  4  3  2  1]
 [ 1  2  1  2  1  2  1  2  1]
 [ 1  2  3  2  3  2  3  2  1]
 [ 1  2  1  0 -1  0  1  2  1]
 [ 1  2  3  2  1  0  1  0  1]
 [ 1  2  1  0  1  0  1  2  1]
 [ 1  0 -1  0  1  0  1  2  1]
 [ 1  0 -1  0 -1  0 -1  0  1]
 [ 1  2  3  4  3  2  1  0  1]
 [ 1  0 -1 -2 -1  0  1  0  1]
 [ 1  0  1  0  1  2  1  2  1]
 [ 1  2  3  2  3  4  3  2  1]
 [ 1  2  1  0  1  2  3  2  1]
 [ 1  0  1